import java.util.ArrayList;

// Euler 29, How many distinct terms are in the sequence generated by a^b for
// 2 <= a <= 100 and 2 <= b <= 100?
public class Euler29 {
	public static ArrayList<Double> combinations = new ArrayList<Double>();
	public static void main(String[] args){
		long start = System.currentTimeMillis();
		for(double a = 2; a <= 100; a++){
			for(double b = 2; b <= 100; b++){
				double temp = Math.pow(a,b);
				if(combinations.contains(temp)){
					
				}else{
					combinations.add(temp);
				}
			}
		}
		long end = System.currentTimeMillis();
		long time = end-start;
		System.out.println("Runtime: " + time + "ms.");
		System.out.println("There are " + combinations.size() + " distinct terms.");
	}
}
